In [1]:
import pandas as pd

In [2]:
df_tecnoempleo = pd.read_csv("../../../CSVs/CSV_manfred/general_limpio_tecnoempleo.csv")

df_manfred = pd.read_csv("../../../CSVs/CSV_tecnoempleo/general_limpio_manfred.csv")

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
df_tecnoempleo

,id,Título,URL,Time Stamp,Fecha publicacion,Habilidades,Nombre de empresa,Ciudad,Teletrabajo,Imprescindible Residir,Funciones,Jornada,Experiencia,Tipo contrato,Formación Mínima,Nivel Profesional,CVs inscritos en el proceso,Salario,Número de puestos,Incentivos,Personas a cargo,+ Países,Info Otros Países,salario_desde,salario_hasta
0,id_tec_1,UrgenteArquitecto Soluciones Observabilidad,https://www.tecnoempleo.com/arquitecto-solucio...,2025-02-22 17:03:04,2025-02-21,"['Arquitecto TIC', 'Técnico de Sistemas']",NPR Spain,100% remoto,Presencial,País Puesto,Arquitecto TIC,Jornada completa,Más de 5 años,Indefinido,Grado Medio,Empleado,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,id_tec_2,UrgenteData Analyst BI - Junior,https://www.tecnoempleo.com/data-analyst-bi-ju...,2025-02-22 17:03:05,2025-02-21,"['Analista', 'Big Data']",Infinity Neural,Barcelona,Híbrido,Provincia Puesto,Analista,Jornada completa,2 años,Indefinido,Grado EEES (Bolonia),Empleado,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,id_tec_3,UrgenteIT Project Manager,https://www.tecnoempleo.com/it-project-manager...,2025-02-22 17:03:06,2025-02-21,"['Arquitecto TIC', 'Inteligencia Artificial/Ma...",Talentea Recruitment,Lleida,Presencial,Provincia Puesto,Arquitecto TIC,Jornada completa,3-5 años,Indefinido,Ingeniero Técnico,Mando Intermedio,4,36.000 € - 60.000 € Bruto/año,NaN,NaN,NaN,NaN,NaN,36.0,60.0
3,id_tec_4,UrgenteSysAdmin/XOps Junior,https://www.tecnoempleo.com/sysadmin-xops-juni...,2025-02-22 17:03:07,2025-02-21,"['Base de Datos/DBA', 'Redes', 'Técnico de Sis...",Beskar Forge,Madrid,Híbrido,NaN,Base de Datos/DBA,Jornada completa,2 años,Indefinido,FP2/Grado Superior,Empleado,44,27.000 € - 30.000 € Bruto/año,2.0,"Flexibilidad, bonuses, extra vacacion+permiso",NaN,NaN,NaN,27.0,30.0
4,id_tec_5,UrgenteIT System Administrator/Web Developer,https://www.tecnoempleo.com/it-system-administ...,2025-02-22 17:03:07,2025-02-21,"['Administrador', 'Programador', 'Técnico de S...",DAC.digital,100% remoto,Presencial,No requerido,Administrador,Jornada completa,3-5 años,Freelance/Autónomo,Sin estudios,Especialista,116,2.700 € - 6.000 € Bruto/mes,NaN,NaN,NaN,NaN,NaN,32.4,72.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3599,id_tec_3600,Administrador Sistemas Linux,https://www.tecnoempleo.com/administrador-sist...,2025-02-22 17:51:38,2018-05-16,['Administrador'],Michael Page,Madrid,Presencial,Provincia Puesto,Administrador,Intensiva Mañana,3 años,Indefinido,FP2/Grado Superior,Especialista,288,33.000 € - 42.000 € Bruto/año,NaN,NaN,NaN,NaN,NaN,33.0,42.0
3600,id_tec_3601,Desarrolladores Java,https://www.tecnoempleo.com/desarrolladores-ja...,2025-02-22 17:51:39,2017-11-08,"['Analista Programador', 'Desarrollador Web', ...",Michael Page,Madrid,Presencial,NaN,Analista Programador,Jornada completa,3 años,Indefinido,Ingeniero Técnico,Empleado,132,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3601,id_tec_3602,Arquitecto Fullstack,https://www.tecnoempleo.com/arquitecto-fullsta...,2025-02-22 17:51:40,2017-10-25,['Arquitecto TIC'],Michael Page,Madrid,Presencial,NaN,Arquitecto TIC,Jornada completa,Más de 5 años,Indefinido,Ingeniero Superior,Empleado,29,30.000 € - 36.000 € Bruto/año,NaN,NaN,NaN,NaN,NaN,30.0,36.0
3602,id_tec_3603,Spark Engineer,https://www.tecnoempleo.com/spark-engineer-mad...,2025-02-22 17:51:40,2017-10-03,"['Arquitecto TIC', 'Desarrollador Web', 'Progr...",Michael Page,Madrid,Presencial,NaN,Arquitecto TIC,Jornada completa,3 años,Indefinido,Ingeniero Técnico,Especialista,44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3603,id_tec_3604,Arquitecto Big Data,https://www.tecnoempleo.com/arquitecto-big-dat...,2025-02-22 17:51:41,2017-09-20,"['Arquitecto TIC', 'Desarrollador Web', 'Progr...",Michael Page,Madrid,Presencial,NaN,Arquitecto TIC,Jornada completa,3 años,Indefinido,Ingeniero Técnico,Especialista,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_manfred

,id,empresa,url,fecha_extraccion,titulo,oferta_activada,Presencial,variable,Teletrabajo,vacaciones,turno_continuo,Salario_desde,Salario_hasta,Jornada
0,id_man_1,geniova,https://www.getmanfred.com/ofertas-empleo/6744...,2025-02-14 11:10:38,Python 3D Developer,1,MADRID,0.0,30,25.0,0,40.0,40.0,JORNADA COMPLETA FLEXIBLE
1,id_man_2,novicap,https://www.getmanfred.com/ofertas-empleo/6677...,2025-02-14 11:10:49,Product Manager,1,BARCELONA,0.0,60,23.0,0,60.0,70.0,JORNADA COMPLETA FLEXIBLE
2,id_man_3,psiconnea,https://www.getmanfred.com/ofertas-empleo/6675...,2025-02-14 11:11:21,Digital Marketing Specialist,1,MADRID,2.0,60,23.0,1,24.0,24.0,JORNADA COMPLETA
3,id_man_4,eri,https://www.getmanfred.com/ofertas-empleo/4193...,2025-02-14 11:11:33,Tech Lead,1,MADRID,0.0,0,23.0,0,55.0,65.0,JORNADA COMPLETA
4,id_man_5,ust,https://www.getmanfred.com/ofertas-empleo/6574...,2025-02-14 11:11:45,.NET Developer,1,MADRID OR SEVILLA OR PALMA,0.0,60,23.0,1,40.0,48.0,JORNADA COMPLETA FLEXIBLE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1221,id_man_1222,product,https://www.getmanfred.com/ofertas-empleo/27/p...,2025-02-14 12:00:22,Frontend Developer Junior,0,NaN,0.0,100,22.0,0,24.0,26.0,JORNADA COMPLETA
1222,id_man_1223,foundernest,https://www.getmanfred.com/ofertas-empleo/23/f...,2025-02-14 12:00:23,Senior Backend Developer,0,MADRID,0.0,100,22.0,0,50.0,60.0,JORNADA COMPLETA
1223,id_man_1224,mindcurv,https://www.getmanfred.com/ofertas-empleo/21/m...,2025-02-14 12:00:25,Senior Java Developer,0,MADRID,0.0,100,30.0,0,45.0,55.0,JORNADA COMPLETA
1224,id_man_1225,mindcurv,https://www.getmanfred.com/ofertas-empleo/18/m...,2025-02-14 12:00:27,Solution Architect,0,NaN,0.0,100,30.0,0,80.0,80.0,JORNADA COMPLETA
1225,id_man_1226,marketgoo,https://www.getmanfred.com/ofertas-empleo/15/m...,2025-02-14 12:00:29,Senior PHP Developer,0,NaN,0.0,100,22.0,0,45.0,55.0,JORNADA COMPLETA

In [6]:
#Renombramos columnas en los df
df_tecnoempleo = df_tecnoempleo.rename(columns={"Título": "titulo", "Nombre de empresa": "empresa", "Ciudad": "ciudad", "Salario_desde": "salario_desde", "Salario_hasta": "salario_hasta", "Jornada": "jornada_tipo", "Teletrabajo": "teletrabajo", "Time Stamp": "timestamp", "Fecha publicacion" : "fecha_publicacion", "Imprescindible Residir" : "imprescindible_residir", "Funciones" : "funciones", "Nivel Profesional" : "nivel_profesional", "CVs inscritos en el proceso" : "cvs_inscritos", "Otras Provincias" : "otras_provincias", "Número de puestos" : "vacantes", "Personas a cargo" : "personas_a_cargo", "+ Países" : "otros_paises", "URL" : "url", "Experiencia" : "experiencia", "Tipo contrato" : "contrato_tipo", "Formación Mínima" : "formacion_minima"})
df_manfred = df_manfred.rename(columns={"Presencial": "ciudad", "Salario_desde": "salario_desde", "Salario_hasta": "salario_hasta", "Jornada": "jornada_tipo", "Teletrabajo": "teletrabajo", "fecha_extraccion" : "timestamp"})

In [7]:
#La columna incentivos en principio no debería estar. Más adelante, eliminar esta línea

df_tecnoempleo.drop(columns = ["Incentivos", "Info Otros Países", "otros_paises"], inplace = True)

In [8]:
df_fusion = pd.concat([df_tecnoempleo, df_manfred], axis=0, join='outer', ignore_index=True)

In [9]:
orden_columnas_fusion = ["id","empresa","titulo","ciudad", "salario_desde", "salario_hasta","variable", "vacaciones", "teletrabajo", "jornada_tipo", "turno_continuo", "imprescindible_residir", "funciones", "contrato_tipo", "nivel_profesional", "formacion_minima", "personas_a_cargo", "experiencia", "vacantes", "cvs_inscritos", "oferta_activada", "fecha_publicacion", "timestamp", "url"]

In [10]:
df_fusion = df_fusion[orden_columnas_fusion]

In [12]:
df_fusion

,id,empresa,titulo,ciudad,salario_desde,salario_hasta,variable,vacaciones,teletrabajo,jornada_tipo,turno_continuo,imprescindible_residir,funciones,contrato_tipo,nivel_profesional,formacion_minima,personas_a_cargo,experiencia,vacantes,cvs_inscritos,oferta_activada,fecha_publicacion,timestamp,url
0,id_tec_1,NPR Spain,UrgenteArquitecto Soluciones Observabilidad,100% remoto,NaN,NaN,NaN,NaN,Presencial,Jornada completa,NaN,País Puesto,Arquitecto TIC,Indefinido,Empleado,Grado Medio,NaN,Más de 5 años,NaN,20.0,NaN,2025-02-21,2025-02-22 17:03:04,https://www.tecnoempleo.com/arquitecto-solucio...
1,id_tec_2,Infinity Neural,UrgenteData Analyst BI - Junior,Barcelona,NaN,NaN,NaN,NaN,Híbrido,Jornada completa,NaN,Provincia Puesto,Analista,Indefinido,Empleado,Grado EEES (Bolonia),NaN,2 años,NaN,23.0,NaN,2025-02-21,2025-02-22 17:03:05,https://www.tecnoempleo.com/data-analyst-bi-ju...
2,id_tec_3,Talentea Recruitment,UrgenteIT Project Manager,Lleida,36.0,60.0,NaN,NaN,Presencial,Jornada completa,NaN,Provincia Puesto,Arquitecto TIC,Indefinido,Mando Intermedio,Ingeniero Técnico,NaN,3-5 años,NaN,4.0,NaN,2025-02-21,2025-02-22 17:03:06,https://www.tecnoempleo.com/it-project-manager...
3,id_tec_4,Beskar Forge,UrgenteSysAdmin/XOps Junior,Madrid,27.0,30.0,NaN,NaN,Híbrido,Jornada completa,NaN,NaN,Base de Datos/DBA,Indefinido,Empleado,FP2/Grado Superior,NaN,2 años,2.0,44.0,NaN,2025-02-21,2025-02-22 17:03:07,https://www.tecnoempleo.com/sysadmin-xops-juni...
4,id_tec_5,DAC.digital,UrgenteIT System Administrator/Web Developer,100% remoto,32.4,72.0,NaN,NaN,Presencial,Jornada completa,NaN,No requerido,Administrador,Freelance/Autónomo,Especialista,Sin estudios,NaN,3-5 años,NaN,116.0,NaN,2025-02-21,2025-02-22 17:03:07,https://www.tecnoempleo.com/it-system-administ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4825,id_man_1222,product,Frontend Developer Junior,NaN,24.0,26.0,0.0,22.0,100,JORNADA COMPLETA,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2025-02-14 12:00:22,https://www.getmanfred.com/ofertas-empleo/27/p...
4826,id_man_1223,foundernest,Senior Backend Developer,MADRID,50.0,60.0,0.0,22.0,100,JORNADA COMPLETA,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2025-02-14 12:00:23,https://www.getmanfred.com/ofertas-empleo/23/f...
4827,id_man_1224,mindcurv,Senior Java Developer,MADRID,45.0,55.0,0.0,30.0,100,JORNADA COMPLETA,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2025-02-14 12:00:25,https://www.getmanfred.com/ofertas-empleo/21/m...
4828,id_man_1225,mindcurv,Solution Architect,NaN,80.0,80.0,0.0,30.0,100,JORNADA COMPLETA,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2025-02-14 12:00:27,https://www.getmanfred.com/ofertas-empleo/18/m...
4829,id_man_1226,marketgoo,Senior PHP Developer,NaN,45.0,55.0,0.0,22.0,100,JORNADA COMPLETA,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2025-02-14 12:00:29,https://www.getmanfred.com/ofertas-empleo/15/m...

In [13]:
df_fusion["teletrabajo"] =  df_fusion["teletrabajo"].apply(lambda x : "Remoto" if x == 100 or x == "Remoto" else "Presencial" if x == 0 or x == "Presencial" else "Hibrido")

df_fusion["jornada_tipo"] = df_fusion["jornada_tipo"].astype(str).str.title()

In [14]:
#Pasamos las columnas fecha_publicacion y timestamp a datetime, 
#errors = coerce convierte los nan a NaT (not a time)
df_fusion["fecha_publicacion"] = pd.to_datetime(df_fusion["fecha_publicacion"], errors = "coerce")
df_fusion["timestamp"] = pd.to_datetime(df_fusion["timestamp"], errors = "coerce")

In [15]:
df_fusion

,id,empresa,titulo,ciudad,salario_desde,salario_hasta,variable,vacaciones,teletrabajo,jornada_tipo,turno_continuo,imprescindible_residir,funciones,contrato_tipo,nivel_profesional,formacion_minima,personas_a_cargo,experiencia,vacantes,cvs_inscritos,oferta_activada,fecha_publicacion,timestamp,url
0,id_tec_1,NPR Spain,UrgenteArquitecto Soluciones Observabilidad,100% remoto,NaN,NaN,NaN,NaN,Presencial,Jornada Completa,NaN,País Puesto,Arquitecto TIC,Indefinido,Empleado,Grado Medio,NaN,Más de 5 años,NaN,20.0,NaN,2025-02-21,2025-02-22 17:03:04,https://www.tecnoempleo.com/arquitecto-solucio...
1,id_tec_2,Infinity Neural,UrgenteData Analyst BI - Junior,Barcelona,NaN,NaN,NaN,NaN,Hibrido,Jornada Completa,NaN,Provincia Puesto,Analista,Indefinido,Empleado,Grado EEES (Bolonia),NaN,2 años,NaN,23.0,NaN,2025-02-21,2025-02-22 17:03:05,https://www.tecnoempleo.com/data-analyst-bi-ju...
2,id_tec_3,Talentea Recruitment,UrgenteIT Project Manager,Lleida,36.0,60.0,NaN,NaN,Presencial,Jornada Completa,NaN,Provincia Puesto,Arquitecto TIC,Indefinido,Mando Intermedio,Ingeniero Técnico,NaN,3-5 años,NaN,4.0,NaN,2025-02-21,2025-02-22 17:03:06,https://www.tecnoempleo.com/it-project-manager...
3,id_tec_4,Beskar Forge,UrgenteSysAdmin/XOps Junior,Madrid,27.0,30.0,NaN,NaN,Hibrido,Jornada Completa,NaN,NaN,Base de Datos/DBA,Indefinido,Empleado,FP2/Grado Superior,NaN,2 años,2.0,44.0,NaN,2025-02-21,2025-02-22 17:03:07,https://www.tecnoempleo.com/sysadmin-xops-juni...
4,id_tec_5,DAC.digital,UrgenteIT System Administrator/Web Developer,100% remoto,32.4,72.0,NaN,NaN,Presencial,Jornada Completa,NaN,No requerido,Administrador,Freelance/Autónomo,Especialista,Sin estudios,NaN,3-5 años,NaN,116.0,NaN,2025-02-21,2025-02-22 17:03:07,https://www.tecnoempleo.com/it-system-administ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4825,id_man_1222,product,Frontend Developer Junior,NaN,24.0,26.0,0.0,22.0,Remoto,Jornada Completa,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaT,2025-02-14 12:00:22,https://www.getmanfred.com/ofertas-empleo/27/p...
4826,id_man_1223,foundernest,Senior Backend Developer,MADRID,50.0,60.0,0.0,22.0,Remoto,Jornada Completa,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaT,2025-02-14 12:00:23,https://www.getmanfred.com/ofertas-empleo/23/f...
4827,id_man_1224,mindcurv,Senior Java Developer,MADRID,45.0,55.0,0.0,30.0,Remoto,Jornada Completa,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaT,2025-02-14 12:00:25,https://www.getmanfred.com/ofertas-empleo/21/m...
4828,id_man_1225,mindcurv,Solution Architect,NaN,80.0,80.0,0.0,30.0,Remoto,Jornada Completa,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaT,2025-02-14 12:00:27,https://www.getmanfred.com/ofertas-empleo/18/m...
4829,id_man_1226,marketgoo,Senior PHP Developer,NaN,45.0,55.0,0.0,22.0,Remoto,Jornada Completa,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaT,2025-02-14 12:00:29,https://www.getmanfred.com/ofertas-empleo/15/m...

In [16]:
df_fusion["oferta_activada"] = df_fusion["oferta_activada"].fillna(1).astype(int)

In [17]:
df_fusion.to_csv("../../../CSVs/CSV_finales_merged/ofertas_final.csv", index=False, encoding="utf-8-sig")

In [18]:
df_habilidades_matriciales_tecnoempleo = pd.read_csv("../../../CSVs/CSV_matriciales/habilidades_matricial_tecnoempleo.csv")

In [19]:
df_habilidades_matriciales_manfred = pd.read_csv("../../../CSVs/CSV_matriciales/habilidades_matricial_manfred.csv")

In [20]:
df_habilidades_matriciales_fusion = pd.concat([df_habilidades_matriciales_manfred, df_habilidades_matriciales_tecnoempleo], axis=0, join='outer', ignore_index=True).fillna(0)

for columna in df_habilidades_matriciales_fusion.columns:
    if columna != "id":
        df_habilidades_matriciales_fusion[columna] = df_habilidades_matriciales_fusion[columna].astype(int)

In [21]:
df_habilidades_matriciales_fusion.to_csv("../../../CSVs/CSV_finales_merged/habilidades_matricial_final.csv, index=False, encoding="utf-8-sig")

In [22]:
def habilidades_relacion (csv = "../../../CSVs/CSV_finales_merged/habilidades_matricial_final.csv", habilidades="../../../CSVs/CSV_finales_merged/habilidades_final.csv", relacion="../../../CSVs/CSV_finales_merged/habilidades_relacion_final.csv"):
    # Ejemplo de DataFrame
    df = pd.read_csv(csv)
    
    # Lo convertimos hacia abajo para que sea mas sencillo
    df_largo = df.melt(id_vars=["id"], var_name="habilidades", value_name="presente")
    #Si es igual a 1 lo mantenemos
    df_largo = df_largo[df_largo["presente"] == 1].drop(columns=["presente"])
    
    #Creamos un df de tecnoligas poniendole un id 
    df_habilidades = pd.DataFrame({"habilidades": df_largo["habilidades"].unique()})
    df_habilidades["hab_id"] = range(1, len(df_habilidades) + 1)
    
    # Relacionamos los dos
    df_relacion = df_largo.merge(df_habilidades, on="habilidades", how="left").drop(columns=["habilidades"])


    df_habilidades.to_csv(habilidades, index = False)
    df_relacion.to_csv(relacion, index = False)

    return df_habilidades, df_relacion

In [23]:
df_tecnologias_matriciales_tecnoempleo = pd.read_csv("../../../CSVs/CSV_matriciales/tecnologias_matricial_tecnoempleo.csv")

In [24]:
df_tecnologias_matriciales_manfred = pd.read_csv("../../../CSVs/CSV_matriciales/tecnologias_matricial_manfred.csv")

In [25]:
df_tecnologias_matriciales_fusion = pd.concat([df_tecnologias_matriciales_manfred, df_tecnologias_matriciales_tecnoempleo], axis=0, join='outer', ignore_index=True).fillna(0)

for columna in df_tecnologias_matriciales_fusion.columns:
    if columna != "id":
        df_tecnologias_matriciales_fusion[columna] = df_tecnologias_matriciales_fusion[columna].astype(int)

In [26]:
df_tecnologias_matriciales_fusion.to_csv("../../../CSVs/CSV_finales_merged/tecnologias_matricial_final.csv", index=False, encoding="utf-8-sig")

In [27]:
def tecnologias_relacion (csv = "../../../CSVs/CSV_finales_merged/tecnologias_matricial_final.csv", tecnologias="../../../CSVs/CSV_finales_merged/tecnologias_final.csv", relacion="../../../CSVs/CSV_finales_merged/relacion_tecnologias_final.csv"):
    # Ejemplo de DataFrame
    df = pd.read_csv(csv)
    
    # Lo convertimos hacia abajo para que sea mas sencillo
    df_largo = df.melt(id_vars=["id"], var_name="tecnologia", value_name="presente")
    #Si es igual a 1 lo mantenemos
    df_largo = df_largo[df_largo["presente"] == 1].drop(columns=["presente"])
    
    #Creamos un df de tecnoligas poniendole un id 
    df_tecnologias = pd.DataFrame({"tecnologia": df_largo["tecnologia"].unique()})
    df_tecnologias["tec_id"] = range(1, len(df_tecnologias) + 1)
    
    # Relacionamos los dos
    df_relacion = df_largo.merge(df_tecnologias, on="tecnologia", how="left").drop(columns=["tecnologia"])


    df_tecnologias.to_csv(tecnologias, index = False)
    df_relacion.to_csv(relacion, index = False)